name: 01-basics

on: workflow_dispatch

jobs:
  testing-now:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "Hello world"
      - name: print testing
        run: echo "testing now..."
