name: 01-basics

run-name: ${{ github.actor }} run this workflow Try number ${{ github.run_number }}

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo ${{ github.actor }}
