name: 02-new-work

run-name: Test marketplace

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      image: mongo:latest

    steps:
      - name: print hello world 1
        run: exit 1

      - name: print hello world 1
        if: failure()
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/karimtarek0000/test-ci-cd/issues \
          -d '{"title":"This is bug", "body":"New bug report submitted." }' \
