name: 02-new-work

run-name: Test marketplace

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    services: 
        image: mongo:latest
      
    steps:
      - name: Print node version
        run: mongos
      
