name: 02-new-work

run-name: Test marketplace

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: node:16
    steps:
      - name: Print node version
        run: node -v
      
