name: 02-new-work

run-name: Test NEEDS

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world 1
        run: echo 'Build Done'
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: print hello world 1
        run: echo 'Done'

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: print hello world 1
        run: echo 'Done'

