name: 02-new-work

run-name: Test marketplace

on: workflow_dispatch

permissions:
   issues: write
  
jobs:
  open-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Open new issue
        run: gh issue create --title "This is a bug" --body "Thank you for opening this issue!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
