name: 02-new-work

run-name: Test marketplace

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
  
      - name: Open new issue
        run: gh issue create --title "This is a first bug" --body "There are alot of bugs" --label "bug"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
