name: 02-new-work

run-name: This is a new workflow

on: workflow_dispatch

permissions:
  issues: write

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/print-some-text
