name: 02-new-work

run-name: This is a new workflow

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world 1
        run: echo ${{ secrets.SECRET_NAME }}
     
