name: Eslint check

run-name: Eslint check

on: pull_request

jobs:
  Eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout

      - name: Install all dependencies
        run: npm install

      - name: Run Eslint check
        run: npm run lint
