name: Fix formatting when merge

run-name: Fix formatting when merge

on:
  push:
    branches:
      - master

jobs:
  Fix-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout

      - name: Install all dependencies
        run: npm install

      - name: Fix Formatting
        run: npm run format

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Fix formatting" || exit 0
          git push
