name: Run all unit test

run-name: Run all unit test on master

on: workflow_dispatch

jobs:
  Run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout

      - name: Clean and install dependencies
        run: |
          npm ci || (rm -rf node_modules package-lock.json && npm install)

      - name: Run Unit Tests
        run: npm run test:cov
