name: Run unit test changed

run-name: Run unit test changed

on: pull_request

jobs:
  Run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/checkout
        with:
          fetch-depth: 0

      - name: Fetch origin branches (for vitest --changed)
        run: git fetch --no-tags --prune --depth=10 origin

      - name: Clean and install dependencies
        run: |
          npm ci || (rm -rf node_modules package-lock.json && npm install)

      - name: Run Unit Tests (Changed files only)
        run: npm run test:changed
